name: Auto Merge Dev to Main

on:
  push:
    branches:
      - dev  # Trigger on push to dev branch

jobs:
  auto_merge:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Git configuration
      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      # Step 3: Fetch the latest branches
      - name: Fetch all branches
        run: git fetch --prune --unshallow

      # Step 4: Merge dev into main
      - name: Merge dev into main
        run: |
          # Checkout the main branch
          git checkout main
          
          # Merge dev into main
          git merge origin/dev --no-ff --no-edit

      # Step 5: Push the merge to main
      - name: Push changes to main
        run: |
          git push origin main

      # Optional: Step 6: Handle any merge conflicts if needed (this can be extended if you want)
      # If there's a merge conflict, the workflow will fail and you may need manual resolution.
