name: Auto Merge Dev to Main (with Open PR)

on:
  push:
    branches:
      - dev  # Trigger on push to dev branch

jobs:
  auto_merge:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Git configuration
      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      # Step 3: Fetch all branches
      - name: Fetch all branches
        run: git fetch --prune --unshallow

      # Step 4: Checkout main and merge dev into main (locally)
      - name: Merge dev into main (locally)
        run: |
          # Checkout the main branch
          git checkout main
          
          # Merge dev into main (without pushing yet)
          git merge origin/dev --no-ff --no-edit

      # Step 5: Push directly to main branch
      - name: Push merged changes to main
        run: |
          git push origin main

      # Step 6: Create Pull Request (optional, if you want manual approval)
      - name: Create Pull Request for manual merge in Databricks
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
            -d '{"title":"Auto-merge changes from dev to main","head":"dev","base":"main"}' \
            "https://api.github.com/repos/${{ github.repository }}/pulls"
