name: Auto Merge PR from Dev to Main

on:
  push:
    branches:
      - dev  # Trigger when changes are pushed to 'dev' branch

jobs:
  create_and_merge_pr:
    runs-on: ubuntu-latest  # Use a runner to execute the job

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checkout the repository to make changes

    - name: Set up GitHub CLI (gh)
      uses: cli/cli-action@v2  # Set up GitHub CLI to interact with GitHub

    - name: Create Pull Request from Dev to Main
      run: |
        PR_TITLE="Auto PR: Merge dev to main"
        PR_BODY="Automated pull request to merge dev into main."
        gh pr create --title "$PR_TITLE" --body "$PR_BODY" --base main --head dev  # Create PR
        gh pr merge --merge --auto --delete-branch  # Merge the PR automatically
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically uses GitHub token for authentication
