name: Auto Merge PR after Push to Dev

on:
  push:
    branches:
      - dev

jobs:
  merge_pr:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Get the latest open PR for dev -> main (or your preferred branch)
      - name: Find and Merge PR
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Fetch all open PRs that are targeting 'main' and have 'dev' as the source branch
          prs=$(curl -s \
            -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/pulls?state=open&base=main&head=${{ github.repository_owner }}:dev")

          # Check if any PR is found
          if [ "$(echo "$prs" | jq 'length')" -gt 0 ]; then
            # Get the first PR ID
            pr_number=$(echo "$prs" | jq '.[0].number')

            # Attempt to merge the PR using the GitHub API
            merge_response=$(curl -s -X PUT \
              -H "Authorization: token $GITHUB_TOKEN" \
              -d '{"merge_method":"merge"}' \
              "https://api.github.com/repos/${{ github.repository }}/pulls/$pr_number/merge")

            # Check if the merge was successful
            if [[ $(echo "$merge_response" | jq -r '.merged') == "true" ]]; then
              echo "PR #$pr_number successfully merged."
            else
              echo "PR #$pr_number merge failed: $(echo "$merge_response" | jq -r '.message')"
              exit 1
            fi
          else
            echo "No open PR found to merge. Skipping."
          fi
